# Generated by Django 3.2.3 on 2021-07-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_projectstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': (('add_project', 'إضافة مشروع'), ('edit_project', 'تعديل مشروع'), ('delete_project', 'حذف مشروع'), ('view_project', 'عرض بيانات مشروع'), ('view_project_balance', 'عرض رصيد مشروع'), ('view_project_statement', 'كشف حساب مشروع'), ('access_project_menu', 'الدخول علي قائمة المشروعات'), ('download_project_data', 'تنزيل بيانات المشاريع'))},
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'default_permissions': (), 'permissions': (('add_project_status', 'إضافة حالة مشروع'), ('edit_project_status', 'تعديل حالة مشروع'), ('delete_project_status', 'حذف حالة مشروع'), ('access_project_status_menu', 'الدخول علي قائمة حالات المشاريع'), ('download_project_status_data', 'تنزيل بيانات حالات المشاريع'))},
        ),
    ]
