# Generated by Django 3.2.3 on 2021-07-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0002_alter_spendcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'default_permissions': (), 'ordering': ['date'], 'permissions': (('undo_save_invoice', 'إعادة فتح الفواتير'), ('add_sales_invoice', 'إضافة فاتورة مبيعات'), ('delete_invoice', 'حذف الفواتير'), ('permanent_delete_invoices', 'حذف نهائي للفواتير'), ('restore_deleted_invoices', 'إستعادة الفواتير المحذوفة'), ('access_sales_invoice_menu', 'عرض فواتير المبيعات'), ('add_reverse_sales_invoice', 'إضافة فاتورة مرتجع مبيعات'), ('access_reverse_sales_invoice_menu', 'عرض فواتير مرتجع المبيعات'), ('add_purchase_invoice', 'إضافة فاتورة مشتريات'), ('access_purchase_invoice_menu', 'عرض فواتير المشتريات'), ('add_reverse_purchase_invoice', 'إضافة فاتورة مرتجع مشتريات'), ('access_reverse_purchase_invoice_menu', 'عرض فواتير مرتجع المشتريات'), ('access_quotation', 'مشاهدة عروض الاسعار'), ('add_quotation', 'إضافة عروض أسعار'), ('add_branch_transfer', 'إضافة تحويل مخزن'), ('delete_branch_transfer', 'حذف تحويل مخزن'), ('access_branch_transfer_menu', 'عرض  تحويل مخزن'), ('add_treasury_transfer', 'إضافة تحويل نقدية'), ('delete_treasury_transfer', 'حذف تحويل نقدية'), ('access_treasury_transfer_menu', 'عرض  تحويل نقدية'), ('add_income_invoice', 'إضافة سند قبض نقدية'), ('delete_income_invoice', 'حذف سند قبض نقدية'), ('access_income_invoice_menu', 'عرض سندات قبض نقدية'), ('add_outcome_invoice', 'إضافة سند صرف نقدية'), ('delete_outcome_invoice', 'حذف سند صرف نقدية'), ('access_outcome_invoice_menu', 'عرض سندات صرف نقدية'), ('add_capital', 'إضافة لرأس المال'), ('minus_capital', 'سحب من رأس المال'), ('add_stock_plus_invoice', 'إضافة فاتورة تسوية زيادة'), ('access_stock_plus_invoice', 'عرض فاتورة تسوية زيادة'), ('add_stock_minus_invoice', 'إضافة فاتورة تسوية عجز'), ('access_stock_minus_invoice', 'عرض فاتورة تسوية عجز'), ('access_sales_invoice_report', 'عرض تقارير فواتير المبيعات'), ('access_reverse_sales_invoice_report', 'عرض تقارير فواتير المبيعات'), ('access_purchase_invoice_report', 'عرض تقارير فواتير المبيعات'), ('access_reverse_purchase_invoice_report', 'عرض تقارير فواتير المبيعات'), ('access_quotation_report', 'عرض تقارير عروض الاسعار'), ('show_profit', 'عرض الارباح'), ('edit_invoice_date', 'تعديل التاريخ في الفاتورة'), ('invoice_discount', 'عمل خصم علي الفاتورة'), ('item_discount', 'عمل خصم علي المنتجات'), ('edit_item_unit_price', 'تعديل سعر المنتج في الفاتورة'), ('edit_invoice_setting', 'تعديل إعدادات الفواتير'), ('edit_invoice_print_setting', 'تعديل إعدادات طباعة الفواتير'), ('add_customer_income', 'قبض سداد عميل/مورد'), ('add_customer_outcome', 'صرف سداد عميل/مورد'), ('search_invoice', 'البحث عن فاتورة'))},
        ),
    ]
