# Generated by Django 3.2.3 on 2021-07-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.IntegerField(choices=[(1, 'فاتورة مبيعات'), (2, 'فاتورة مبيعات توصيل'), (3, 'فاتورة مبيعات موقع'), (4, 'فاتورة مرتجع مبيعات'), (5, 'فاتورة مشتريات'), (6, 'فاتورة مرتجع مشتريات'), (7, 'عرض أسعار'), (8, 'مصروفات عامة'), (9, 'دخل عام'), (10, 'حساب جاري الشركاء'), (11, 'إذن صرف نقدية'), (12, 'إذن قبض نقدية'), (13, 'إضافة رأس مال'), (14, 'سحب من رأس المال'), (15, 'فاتورة تسوية عجز'), (16, 'فاتورة تسوية زيادة'), (17, 'تحويل مخزون'), (19, 'تحويل خزينة'), (21, 'قبض سداد'), (22, 'صرف سداد'), (23, 'فاتورة شيفت'), (24, 'قيد يومي')], verbose_name='نوع الفاتورة'),
        ),
    ]
