# Generated by Django 3.2.3 on 2021-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان الرئيسية')),
                ('index_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='وصف الرئيسية')),
                ('index_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة الرئيسية')),
            ],
        ),
    ]
