# Generated by Django 3.2.3 on 2021-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_rename_index_logo_mainpage_index_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='about_item1_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العنصر الاول في من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_item1_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان العنصر الاول في من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_item2_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العنصر الثاني في من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_item2_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان العنصر الثاني في من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_item3_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان العنصر الثالث في من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_item4_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العنصر الثالث في من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان من نحن'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_vedio',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='لينك فيديو من نحن'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='index_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الرئيسية'),
        ),
    ]
