# Generated by Django 3.2.3 on 2021-07-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20210713_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='about_item4_text',
            new_name='about_item3_text',
        ),
    ]
