# Generated by Django 3.2.3 on 2021-07-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20210713_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='service_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف خدماتنا'),
        ),
    ]
