# Generated by Django 3.2.3 on 2021-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_mainpage_service_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='about_title',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='call_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف تواصل معنا'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='product_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف منتجاتنا'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='team_text',
            field=models.TextField(blank=True, null=True, verbose_name='وصف فريقنا'),
        ),
    ]
