# Generated by Django 3.2.3 on 2021-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_mainpage_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
        ),
    ]
