# Generated by Django 3.2.3 on 2021-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_statisticsitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutitems',
            name='description',
            field=models.TextField(default=0, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutitems',
            name='title',
            field=models.CharField(default=0, max_length=128, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statisticsitems',
            name='number',
            field=models.IntegerField(default=0, verbose_name='الرقم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statisticsitems',
            name='title',
            field=models.CharField(default=0, max_length=128, verbose_name='العنوان'),
            preserve_default=False,
        ),
    ]
