# Generated by Django 3.2.3 on 2021-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_auto_20210715_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='الوصف')),
            ],
        ),
    ]
