# Generated by Django 3.2.3 on 2021-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_serviceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitems',
            name='title',
            field=models.CharField(default=0, max_length=128, verbose_name='العنوان'),
            preserve_default=False,
        ),
    ]
