# Generated by Django 3.2.3 on 2021-07-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_serviceitems_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='العنوان')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
