# Generated by Django 3.2.3 on 2021-07-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': (), 'permissions': (('add_employee', 'إضافة موظف'), ('edit_employee', 'تعديل موظف'), ('delete_employee', 'حذف موظف'), ('view_employee', 'عرض قائمة الموظفين'), ('add_employee_user', 'إضافة حساب لموظف'), ('view_employee_data', 'عرض بيانات الموظف'), ('login_as_employee', 'الدخول كموظف'), ('add_employee_permission', 'إضافة صلاحيات للموظف'), ('show_number_of_sales_per_day', 'عرض عدد المبيعات لكل يوم'), ('show_percentage_of_sales_to_expenses', 'عرض نسبة المبيعات للمصروفات'), ('stock_search', 'بحث عن مخزون'), ('product_search', 'بحث عن منتج'), ('employee_search', ' بحث عن عميل / مورد'), ('show_open_invoices', 'عرض الفواتير المفتوحة'), ('show_sales_value', 'عرض مبيعات اليوم'), ('show_today_calls', 'عرض مكالمات اليوم'), ('show_number_of_new_clients', 'عرض عدد العملاء الجدد للشهر'), ('show_expenses_value', 'عرض مصروفات اليوم'))},
        ),
    ]
