# Generated by Django 3.2.3 on 2021-07-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': (), 'permissions': (('add_employee', 'إضافة موظف'), ('edit_employee', 'تعديل موظف'), ('delete_employee', 'حذف موظف'), ('view_employee', 'عرض قائمة الموظفين'), ('add_employee_user', 'إضافة حساب لموظف'), ('view_employee_data', 'عرض بيانات الموظف'), ('login_as_employee', 'الدخول كموظف'), ('add_employee_permission', 'إضافة صلاحيات للموظف'), ('show_number_of_sales_per_day', 'عرض عدد المبيعات لكل يوم'), ('show_percentage_of_sales_to_expenses', 'عرض نسبة المبيعات للمصروفات'), ('stock_search', 'بحث عن مخزون'), ('product_search', 'بحث عن منتج'), ('employee_search', ' بحث عن عميل / مورد'), ('show_open_invoices', 'عرض الفواتير المفتوحة'), ('show_sales_value', 'عرض مبيعات اليوم'), ('show_today_calls', 'عرض مكالمات اليوم'), ('show_number_of_new_clients', 'عرض عدد العملاء الجدد للشهر'), ('show_expenses_value', 'عرض مصروفات اليوم'), ('access_financial_statement_report', 'الدخول على تقرير القائمة المالية'), ('access_profits_losses_report', 'الدخول على تقرير الأرباح والخسائر'), ('show_expenses_report', 'عرض تقارير المصروفات'), ('show_receipts_report', 'عرض تقارير المقبوضات'), ('show_new_clients_report', 'عرض تقارير العملاء الجدد'), ('show_calls_report', 'عرض تقارير المكالمات'), ('download_employee_data', 'تنزيل بيانات الموظفين'))},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'default_permissions': (), 'permissions': (('add_job_title', 'إضافة مسمى وظيفي'), ('edit_job_title', 'تعديل مسمى وظيفي'), ('delete_job_title', 'حذف مسمى وظيفي'), ('view_job_title', 'عرض قائمة المسميات الوظيفية'), ('download_job_title_data', 'تنزيل بيانات المسميات الوظيفية'))},
        ),
    ]
