# Generated by Django 3.2.3 on 2021-07-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_alter_treasury_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'default_permissions': (), 'permissions': (('add_branch', 'إضافة فرع'), ('edit_branch', 'تعديل فرع'), ('delete_branch', 'حذف فرع'), ('access_branch_menu', 'الدخول علي قائمة الفروع'), ('download_branch_data', 'تنزيل بيانات الفروع'))},
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'default_permissions': (), 'permissions': (('add_treasury', 'إضافة خزينة و حساب بنكي'), ('edit_treasury', 'تعديل خزينة و حساب بنكي'), ('delete_treasury', 'حذف خزينة و حساب بنكي'), ('access_treasury_menu', 'الدخول علي قائمة الخزائن والحسابات البنكية'), ('download_treasury_data', 'تنزيل بيانات الخزائن'))},
        ),
    ]
