# Generated by Django 3.2.3 on 2021-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0003_auto_20210706_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasury',
            options={'default_permissions': (), 'permissions': (('add_treasury', 'إضافة خزينة و حساب بنكي'), ('edit_treasury', 'تعديل خزينة و حساب بنكي'), ('delete_treasury', 'حذف خزينة و حساب بنكي'), ('access_treasury_menu', 'الدخول علي قائمة الخزائن والحسابات البنكية'), ('download_treasury_data', 'تنزيل بيانات الخزائن'), ('access_treasury_balances_report', 'الدخول لتقرير أرصدة الخزائن'), ('access_treasury_moves_report', 'الدخول على تقرير حركات الخزائن'))},
        ),
    ]
