# Generated by Django 3.2.3 on 2021-06-02 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '__first__'),
        ('Branches', '0001_initial'),
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاريخ و وقت الطلب')),
                ('status', models.IntegerField(choices=[(1, 'مفتوح'), (2, 'منتهي'), (3, 'ملغي')], default=1, verbose_name='حالة الطلب')),
                ('taxes', models.FloatField(default=0.0, verbose_name='الضرائب')),
                ('total', models.FloatField(default=0.0, verbose_name='المبلغ الكلي')),
                ('total_paid', models.FloatField(default=0.0, verbose_name='المبلغ المدفوع')),
                ('discount_type', models.IntegerField(choices=[(1, 'نسبة'), (2, 'قيمة ثابتة')], default=1, verbose_name='نوع الخصم')),
                ('discount_value', models.FloatField(default=0.0, verbose_name='قيمة الخصم')),
                ('delivery_cost', models.FloatField(default=0.0, verbose_name='تكلفة التوصيل')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.address', verbose_name='عنوان العميل')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customer', verbose_name='العميل')),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'مطعم'), (2, 'محل'), (3, 'خدمة توصيل')], null=True, verbose_name='النوع')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انشأت بواسطة')),
                ('employees', models.ManyToManyField(to='HR.Employee', verbose_name='الموظف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branches.branch', verbose_name='تابع لمخزن')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='التاريخ')),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime(2021, 6, 2, 18, 59, 40, 777098, tzinfo=utc), verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, default=datetime.datetime(2021, 6, 2, 18, 59, 40, 777098, tzinfo=utc), verbose_name='وقت النهاية')),
                ('cashier_no', models.CharField(blank=True, max_length=128, null=True, verbose_name='رقم الكاشير')),
                ('status', models.IntegerField(choices=[(1, 'مغلق'), (2, 'مفتوح')], default=2, verbose_name='حالة الشيفت')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.employee', verbose_name='الموظف')),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.pos', verbose_name='تابع لنقطة')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('dicount', models.FloatField(default=0.0, verbose_name='الخصم')),
                ('taxes', models.FloatField(default=0.0, verbose_name=' الضرائب')),
                ('total_wo_taxes', models.FloatField(default=0.0, verbose_name='الكلي بدون ضرائب')),
                ('sub_total', models.FloatField(default=0.0, verbose_name='المبلغ الكلي')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.order', verbose_name='رقم الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='الصنف')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.pos', verbose_name='نقطة البيع'),
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.shift', verbose_name='تابع لشيفت'),
        ),
    ]
