# Generated by Django 3.2.3 on 2021-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20210603_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'كاش'), (2, 'فيزا')], default=1, verbose_name='طريقة الدفع'),
        ),
    ]
