# Generated by Django 3.2.3 on 2021-06-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20210603_2020'),
        ('POS', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.employee', verbose_name='مندوب التوصيل'),
        ),
    ]
