# Generated by Django 3.2.3 on 2021-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_order_delivery_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='pos',
            name='country_delivery_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر توصيل الدولة'),
        ),
        migrations.AddField(
            model_name='pos',
            name='governorate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='pos',
            name='governorate_delivery_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر توصيل المحافظة'),
        ),
        migrations.AddField(
            model_name='pos',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='الإقليم'),
        ),
    ]
