# Generated by Django 3.2.3 on 2021-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0007_auto_20210629_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='country_delivery_cost',
            field=models.FloatField(default=0, verbose_name='سعر توصيل الدولة'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='governorate_delivery_cost',
            field=models.FloatField(default=0, verbose_name='سعر توصيل المحافظة'),
        ),
    ]
