# Generated by Django 3.2.3 on 2021-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_auto_20210629_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='service',
            field=models.FloatField(default=0, verbose_name='سعر الخدمة'),
        ),
    ]
