# Generated by Django 3.2.3 on 2021-07-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Partners', '0001_initial'),
        ('POS', '0012_pos_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Partners.partner', verbose_name='الشريك'),
        ),
    ]
