# Generated by Django 3.2.3 on 2021-07-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0013_order_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos',
            options={'default_permissions': (), 'permissions': (('add_pos', 'إضافة نقاط البيع'), ('edit_pos', 'تعديل نقاط البيع'), ('delete_pos', 'حذف نقاط البيع'), ('view_pos', 'عرض نقاط البيع'), ('view_pos_detail', 'عرض بيانات نقاط البيع'), ('enter_pos', 'الدخول لنقطة البيع'), ('download_pos_data', 'تنزيل بيانات نقاط البيع'))},
        ),
    ]
