# Generated by Django 3.2.3 on 2021-07-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_alter_customer_options'),
        ('POS', '0014_alter_pos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosBaseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_customer_in_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customers.customer', verbose_name='العميل الافتراضي للطلبات')),
            ],
        ),
    ]
