# Generated by Django 3.2.3 on 2021-07-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0015_posbasesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posbasesetting',
            options={'default_permissions': (), 'permissions': (('edit_pos_setting', 'تعديل إعدادات نقطة البيع'),)},
        ),
    ]
