# Generated by Django 3.2.3 on 2021-07-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0005_alter_branch_options'),
        ('POS', '0016_alter_posbasesetting_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='from_treasury',
        ),
        migrations.AddField(
            model_name='pos',
            name='to_treasury',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branches.treasury', verbose_name='الى خزينة'),
        ),
    ]
