# Generated by Django 3.2.3 on 2021-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'default_permissions': (), 'permissions': (('add_address', 'إضافة عنوان '), ('edit_address', 'تعديل عنوان'), ('delete_address', 'حذف عنوان'), ('access_address_menu', 'الدخول علي قائمة العناوين'))},
        ),
        migrations.AlterModelOptions(
            name='callreason',
            options={'default_permissions': (), 'permissions': (('add_call_reason', 'إضافة سبب إتصال '), ('edit_call_reason', 'تعديل سبب إتصال'), ('delete_call_reason', 'حذف سبب إتصال'), ('access_call_reason_menu', 'الدخول علي قائمة أسباب الإتصال'))},
        ),
        migrations.AlterModelOptions(
            name='customercall',
            options={'default_permissions': (), 'permissions': (('add_customer_call', 'إضافة مكالمة '), ('edit_customer_call', 'تعديل مكالمة'), ('delete_customer_call', 'حذف مكالمة'), ('access_customer_call_menu', 'الدخول علي قائمة المكالمات'))},
        ),
    ]
