# Generated by Django 3.2.3 on 2021-06-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20210627_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CustomerGroup',
        ),
    ]
