# Generated by Django 3.2.3 on 2021-06-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_rename_group_customergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الموبايل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customer', verbose_name='الموظف')),
            ],
            options={
                'permissions': (('add_customer_phone', 'إضافة رقم العميل / المورد '), ('edit_customer_phone', 'تعديل رقم العميل / المورد'), ('delete_customer_phone', 'حذف رقم العميل / المورد'), ('access_customer_phone_menu', 'الدخول علي قائمة ارقام الموظف')),
                'default_permissions': (),
            },
        ),
    ]
