# Generated by Django 3.2.3 on 2021-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_auto_20210628_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area_delivery_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر توصيل المنطقة'),
        ),
    ]
