# Generated by Django 3.2.3 on 2021-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_address_area_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area_delivery_cost',
            field=models.FloatField(default=0, verbose_name='سعر توصيل المنطقة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_delivery_cost',
            field=models.FloatField(default=0, verbose_name='سعر توصيل الدولة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='governorate_delivery_cost',
            field=models.FloatField(default=0, verbose_name='سعر توصيل المحافظة'),
        ),
    ]
