# Generated by Django 3.2.3 on 2021-07-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_auto_20210629_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callreason',
            options={'default_permissions': (), 'permissions': (('add_call_reason', 'إضافة سبب إتصال '), ('edit_call_reason', 'تعديل سبب إتصال'), ('delete_call_reason', 'حذف سبب إتصال'), ('access_call_reason_menu', 'الدخول علي قائمة أسباب الإتصال'), ('download_call_reason_data', 'تنزيل بيانات أسباب الإتصال'))},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': (), 'permissions': (('add_customer_category', 'إضافة شريحة عملاء'), ('edit_customer_category', 'تعديل شريحة عملاء'), ('delete_customer_category', 'حذف شريحة عملاء'), ('access_customer_category_menu', 'الدخول علي قائمة شرائح العملاء'), ('download_customer_category_data', 'تنزيل بيانات شرائح العملاء'))},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': (('add_customer', 'إضافة عميل/مورد'), ('edit_customer', 'تعديل عميل/مورد'), ('delete_customer', 'حذف عميل/مورد'), ('view_customer', 'عرض بيانات عميل/مورد'), ('view_customer_balance', 'عرض رصيد عميل/مورد'), ('view_customer_statement', 'كشف حساب عميل/مورد'), ('access_customer_menu', 'الدخول علي قائمة العملاء/الموردين'), ('download_customer_data', 'تنزيل بيانات العملاء'))},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'default_permissions': (), 'permissions': (('add_customer_rating', 'إضافة تصنيف عملاء'), ('edit_customer_rating', 'تعديل تصنيف عملاء'), ('delete_customer_rating', 'حذف تصنيف عملاء'), ('access_customer_rating_menu', 'الدخول علي قائمة تصنيفات العملاء'), ('download_customer_rating_data', 'تنزيل بيانات تصنيفات العملاء'))},
        ),
    ]
