# Generated by Django 3.2.3 on 2021-07-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_auto_20210705_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': (('add_customer', 'إضافة عميل/مورد'), ('edit_customer', 'تعديل عميل/مورد'), ('delete_customer', 'حذف عميل/مورد'), ('view_customer', 'عرض بيانات عميل/مورد'), ('view_customer_balance', 'عرض رصيد عميل/مورد'), ('view_customer_statement', 'كشف حساب عميل/مورد'), ('access_customer_menu', 'الدخول علي قائمة العملاء/الموردين'), ('download_customer_data', 'تنزيل بيانات العملاء'), ('access_customer_account_statement', 'الدخول على كشف حساب عميل/مورد'), ('access_creditors_report', 'الدخول على تقرير الدائنون (له)'), ('access_debtors_report', 'الدخول على تقرير المدينون (عليه)'), ('access_idle_customer_report', 'الدخول على تقارير العملاء الخاملين'), ('access_customer_report', 'الدخول على تقارير العملاء/الموردين'), ('access_customer_best_seller_report', 'الدخول على تقارير العملاء/الموردين الأكثر مبيعاً'))},
        ),
    ]
