# Generated by Django 3.2.3 on 2021-06-28 10:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='العنوان')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
    ]
