# Generated by Django 3.2.3 on 2021-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20210603_2020'),
        ('Information', '0002_alter_information_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('employee', models.ManyToManyField(to='HR.Employee', verbose_name='الموظفين')),
            ],
            options={
                'permissions': (('add_information_category', 'إضافة تصنيف معلومة'), ('edit_information_category', 'تعديل تصنيف معلومة'), ('delete_information_category', 'حذف تصنيف معلومة'), ('view_informations_category_list', 'الدخول على قائمة تصنيفات المعلومات الإدارية')),
                'default_permissions': (),
            },
        ),
    ]
