# Generated by Django 3.2.3 on 2021-06-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0003_informationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Information.informationcategory', verbose_name='التصنيف'),
        ),
    ]
