# Generated by Django 3.2.3 on 2021-06-30 11:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Information', '0004_information_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
