# Generated by Django 3.2.3 on 2021-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulessetting',
            name='pos_module',
            field=models.BooleanField(default=False, verbose_name='نقاط البيع'),
        ),
    ]
