# Generated by Django 3.2.3 on 2021-06-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
            options={
                'permissions': (('add_brand', 'إضافة براند'), ('edit_brand', 'تعديل براند'), ('delete_brand', 'حذف براند'), ('access_brand_menu', 'الدخول علي قائمة البراندات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
            options={
                'permissions': (('add_main_category', 'إضافة تصنيف رئيسي للمنتجات'), ('edit_main_category', 'تعديل تصنيف رئيسي للمنتجات'), ('delete_main_category', 'حذف تصنيف رئيسي للمنتجات'), ('access_main_category_menu', 'الدخول علي التصنيف الرئيسية للمنتجات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
            options={
                'permissions': (('add_manufacture', 'إضافة جهة مصنعة للمنتجات'), ('edit_manufacture', 'تعديل جهة مصنعة للمنتجات'), ('delete_manufacture', 'حذف جهة مصنعة للمنتجات'), ('access_manufacture_menu', 'الدخول علي قائمة الجهات المصنعة')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'مبلغ ثابت'), (2, 'نسبة')], default=2, verbose_name='النوع')),
                ('value', models.FloatField(default=0.0, verbose_name='القيمة')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.maincategory', verbose_name='المجموعة الرئيسية')),
            ],
            options={
                'permissions': (('add_sub_category', 'إضافة تصنيف فرعي للمنتجات'), ('edit_sub_category', 'تعديل تصنيف فرعي للمنتجات'), ('delete_sub_category', 'حذف تصنيف فرعي للمنتجات'), ('access_sub_category_menu', 'الدخول علي التصنيف الفرعية للمنتجات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(choices=[(1, 'منتج عادي'), (2, 'منتج مجمع'), (3, 'خدمة')], default=1, verbose_name='النوع')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('purchase_price', models.FloatField(default=0.0, verbose_name='سعر الشراء')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='سعر التكلفة')),
                ('sell_price', models.FloatField(default=0.0, verbose_name='سعر البيع')),
                ('amount_in_sub_unit', models.FloatField(default=0.0, verbose_name='العدد في الوحدة الفرعية')),
                ('amount_in_sub_sub_unit', models.FloatField(default=0.0, verbose_name='العدد في الوحدة الفرعية2')),
                ('max_sell', models.FloatField(blank=True, null=True, verbose_name='حد الصرف')),
                ('full_stock', models.FloatField(blank=True, null=True, verbose_name='حد الطلب')),
                ('critical_stock', models.FloatField(default=1, verbose_name='الرصيد الحرج')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.brand', verbose_name='البراند')),
                ('main_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_unit', to='Products.unit', verbose_name='الوحدة الاساسية')),
                ('manufacture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.manufacture', verbose_name='الجهة المصنعة')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.subcategory', verbose_name='المجموعة')),
                ('sub_sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sub_unit', to='Products.unit', verbose_name='الوحدة الفرعية2')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_unit', to='Products.unit', verbose_name='الوحدة الفرعية')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.tax', verbose_name='الضريبة المضافة')),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('add_product', 'إضافة منتج'), ('edit_product', 'تعديل منتج'), ('delete_product', 'حذف منتج'), ('view_purchase_price', 'مشاهدة سعر الشراء'), ('view_cost_price', 'مشاهدة سعر التكلفة'), ('access_product_menu', 'الدخول علي قائمة المنتجات')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('contain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='Products.product', verbose_name='المنتج')),
                ('grouped_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_item', to='Products.product', verbose_name='المنتج المجمع')),
            ],
        ),
    ]
