# Generated by Django 3.2.3 on 2021-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupedproduct',
            options={'default_permissions': (), 'permissions': (('add_group_product', 'إضافة مكونات منتج'), ('edit_group_product', 'تعديل مكونات منتج'), ('delete_group_product', 'حذف مكونات منتج'), ('access_group_product_menu', 'الدخول علي قائمة مكونات المنتجات'))},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': (('add_product', 'إضافة منتج'), ('edit_product', 'تعديل منتج'), ('delete_product', 'حذف منتج'), ('view_purchase_price', 'مشاهدة سعر الشراء'), ('view_cost_price', 'مشاهدة سعر التكلفة'), ('access_product_menu', 'الدخول علي قائمة المنتجات'), ('access_product_detail', 'الدخول علي تفاصيل المنتج'), ('print_product_label', 'طباعة ملصقات المنتج'))},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'default_permissions': (), 'permissions': (('add_tax', 'إضافة ضريبة'), ('edit_tax', 'تعديل ضريبة'), ('delete_tax', 'حذف ضريبة'), ('access_tax_menu', 'الدخول علي قائمة الضرائب'))},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'default_permissions': (), 'permissions': (('add_unit', 'إضافة وحدة'), ('edit_unit', 'تعديل وحدة'), ('delete_unit', 'حذف وحدة'), ('access_unit_menu', 'الدخول علي قائمة الوحدات'))},
        ),
        migrations.AddField(
            model_name='groupedproduct',
            name='unit',
            field=models.IntegerField(choices=[(1, 'طن'), (2, 'كيلو'), (3, 'جرام'), (4, 'متر مكعب'), (5, 'سانتي متر مكعب'), (6, 'لتر'), (7, 'ملي لتر'), (8, 'قطعة'), (9, 'كرتونة')], default=8, verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='اسم الضريبة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_unit',
            field=models.IntegerField(choices=[(1, 'طن'), (2, 'كيلو'), (3, 'جرام'), (4, 'متر مكعب'), (5, 'سانتي متر مكعب'), (6, 'لتر'), (7, 'ملي لتر'), (8, 'قطعة'), (9, 'كرتونة')], default=8, verbose_name='الوحدة الرئيسية'),
        ),
    ]
