# Generated by Django 2.2 on 2021-06-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_auto_20210603_2020'),
        ('Products', '0002_auto_20210603_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('discount', models.FloatField(default=0.0, verbose_name='نسبة الخصم ')),
                ('opration', models.IntegerField(choices=[(1, '-'), (2, '+')], default=1, verbose_name='العملية')),
                ('new_price', models.FloatField(default=0.0, verbose_name='السعر بعد الخصم')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='الترتيب')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('deleted', models.BooleanField(default=False, verbose_name='مسح')),
                ('inactive', models.BooleanField(default=False, verbose_name='تعطيل الشريحة')),
                ('customer_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.Category', verbose_name='الشريحة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='اسم المنتج')),
            ],
        ),
    ]
